(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self,m=function(a){return a};var aa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var p,q;a:{for(var ba=["CLOSURE_FLAGS"],r=l,t=0;t<ba.length;t++)if(r=r[ba[t]],null==r){q=null;break a}q=r}var ca=q&&q[610401301];p=null!=ca?ca:!1;var u;const da=l.navigator;u=da?da.userAgentData||null:null;function v(a){return p?u?u.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function w(a){var b;a:{if(b=l.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function x(){return p?!!u&&0<u.brands.length:!1}function ea(){return x()?v("Chromium"):(w("Chrome")||w("CriOS"))&&!(x()?0:w("Edge"))||w("Silk")};var fa=x()?!1:w("Trident")||w("MSIE");!w("Android")||ea();ea();w("Safari")&&(ea()||(x()?0:w("Coast"))||(x()?0:w("Opera"))||(x()?0:w("Edge"))||(x()?v("Microsoft Edge"):w("Edg/"))||x()&&v("Opera"));var ja={},y=null;var ka="undefined"!==typeof Uint8Array,la=!fa&&"function"===typeof btoa;const z="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;function A(a,b){z?a[z]|=b:void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function ma(a){const b=B(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=Array.prototype.slice.call(a)),C(a,b|1))}function B(a){let b;z?b=a[z]:b=a.g;return b|0}function C(a,b){z?a[z]=b:void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a}
function na(a){A(a,1);return a}function oa(a){A(a,16);return a}function pa(a,b){C(b,(a|0)&-51)}function qa(a,b){C(b,(a|18)&-41)};var D={};function E(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let ra;var F=Object.freeze(C([],23));function sa(a){if(a&2)throw Error();};function ta(a,b,c){var d=!1;if(null!=a&&"object"===typeof a&&!(d=Array.isArray(a))&&a.l===D)return a;if(d){var e=d=B(a);0===e&&(e|=c&16);e|=c&2;e!==d&&C(a,e);return new b(a)}};var G=function(a,b,c){return-1===b?null:b>=a.i?a.g?a.g[b]:void 0:c&&a.g&&(c=a.g[b],null!=c)?c:a.h[b+-1]},H=function(a,b,c,d){a.j&&(a.j=void 0);if(b>=a.i||d)return d=a.i+-1,(a.g||(a.g=a.h[d]={}))[b]=c,a;a.h[b+-1]=c;(c=a.g)&&b in c&&delete c[b];return a},L=function(a,b,c){return void 0!==I(a,b,J(a,K,c))},ua=function(a,b){a=G(a,b);return null==a?a:!!a};function va(a,b,c,d){sa(B(a.h));c!==d?H(a,b,c):H(a,b,void 0,!1);return a}
var J=function(a,b,c){return wa(a,b)===c?c:-1},wa=function(a,b){let c=0;for(let d=0;d<b.length;d++){const e=b[d];null!=G(a,e)&&(0!==c&&H(a,c,void 0,!1),c=e)}return c},I=function(a,b,c,d){const e=G(a,c,d);b=ta(e,b,B(a.h));b!==e&&null!=b&&H(a,c,b,d);return b},M=function(a,b,c){b=I(a,b,c,!1);if(null==b)return b;if(!(B(a.h)&2)){const d=xa(b);d!==b&&(b=d,H(a,c,b,!1))}return b},za=function(a,b){var c=B(a.h),d=!!(c&2);var e=d?1:2,h=!!(c&2),f=h,g=G(a,b);Array.isArray(g)||(g=F);var k=B(g);k&1||na(g);f?k&2||
A(g,18):k&16&&!(k&2)&&(f=g,z?f[z]&&(f[z]&=-17):void 0!==f.g&&(f.g&=-17));if(g!==F&&B(g)&4)3===e||h||(h=Object.isFrozen(g),1===e?h||Object.freeze(g):(e=B(g),c=e&-19,h&&(g=Array.prototype.slice.call(g),e=0,H(a,b,g)),e!==c&&C(g,c))),a=g;else{f=g;k=ya;h=!!(c&2);var n=!!(B(f)&2);g=f;!h&&n&&(f=Array.prototype.slice.call(f));var R=c|(n?2:0);c=n;let ha=n=0;for(;n<f.length;n++){const ia=ta(f[n],k,R);void 0!==ia&&(c||(c=!!(2&B(ia.h))),f[ha++]=ia)}ha<n&&(f.length=ha);k=B(f);R=k|5;c=c?R&-9:R|8;k!=c&&(Object.isFrozen(f)&&
(f=Array.prototype.slice.call(f)),C(f,c));g!==f&&H(a,b,f);(h||1===e)&&Object.freeze(f);a=f}if(!(d||B(a)&8)){for(d=0;d<a.length;d++)b=a[d],e=xa(b),b!==e&&(a[d]=e);A(a,8)}return a},N=function(a,b){a=ua(a,b);return null==a?!1:a},O=function(a,b){a:if(a=G(a,b),null!=a){switch(typeof a){case "string":a=+a;break a;case "number":break a}a=void 0}return null==a?0:a},P=function(a,b){a=G(a,b);return null==a?"":a};let Q;function Aa(a,b){Q=b;a=new a(b);Q=void 0;return a};function Ba(a,b){return Ca(b)}
function Ca(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&ka&&null!=a&&a instanceof Uint8Array){if(la){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!y){y={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=","+/","-_=","-_.","-_"];for(var e=
0;5>e;e++){var h=c.concat(d[e].split(""));ja[e]=h;for(var f=0;f<h.length;f++){var g=h[f];void 0===y[g]&&(y[g]=f)}}}b=ja[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=h=0;h<a.length-2;h+=3){var k=a[h],n=a[h+1];g=a[h+2];f=b[k>>2];k=b[(k&3)<<4|n>>4];n=b[(n&15)<<2|g>>6];g=b[g&63];c[e++]=""+f+k+n+g}f=0;g=d;switch(a.length-h){case 2:f=a[h+1],g=b[(f&15)<<2]||d;case 1:a=a[h],c[e]=""+b[a>>2]+b[(a&3)<<4|f>>4]+g+d}a=c.join("")}return a}}return a};function Da(a,b){const c=Array.prototype.slice.call(a.h),d=a.g;var e=c.length+(d?-1:0);let h=0;for(;h<e;h++)c[h]=b(c[h]);if(d){e=c[h]={};for(const f in d)e[f]=b(d[f])}b=Aa(a.constructor,oa(c));a.m&&(b.m=a.m.slice());return b}function Ea(a,b,c,d,e,h){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&B(a)&1?void 0:h&&B(a)&2?a:Fa(a,b,c,void 0!==d,e,h);else if(E(a)){const f={};for(let g in a)f[g]=Ea(a[g],b,c,d,e,h);a=f}else a=b(a,d);return a}}
function Fa(a,b,c,d,e,h){const f=d||c?B(a):0;d=d?!!(f&16):void 0;a=Array.prototype.slice.call(a);for(let g=0;g<a.length;g++)a[g]=Ea(a[g],b,c,d,e,h);c&&c(f,a);return a}function Ga(a){return a.l===D?a.toJSON():Ca(a)};function Ha(a,b,c=qa){if(null!=a){if(ka&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){const d=B(a);if(d&2)return a;if(b&&!(d&32)&&(d&16||0===d))return C(a,d|18),a;a=Fa(a,Ha,d&4?qa:c,!0,!1,!0);b=B(a);b&4&&b&2&&Object.freeze(a);return a}a.l===D&&(B(a.h)&2||(a=Ia(a,!0),A(a.h,18)));return a}}function Ia(a,b){const c=B(a.h),d=b||c&2?qa:pa,e=!!(c&16);return Da(a,h=>Ha(h,e,d))}function xa(a){if(!(B(a.h)&2))return a;const b=Ia(a,!1);b.j=a;return b};var S=class{constructor(a){null==a&&(a=Q);Q=void 0;if(null==a)a=[],C(a,48);else{if(!Array.isArray(a))throw Error();A(a,32)}this.h=a;a:{var b=this.h.length;a=b-1;if(b&&(b=this.h[a],E(b))){this.g=b;this.i=a- -1;break a}this.i=Number.MAX_VALUE}}toJSON(){if(ra)var a=Ja(this,this.h,!1);else a=Fa(this.h,Ga,void 0,void 0,!1,!1),a=Ja(this,a,!0);return a}};S.prototype.l=D;S.prototype.toString=function(){return Ja(this,this.h,!1).toString()};
function Ja(a,b,c){const d=a?a.constructor.o:void 0;var e=a.i;if(d){if(!c){b=Array.prototype.slice.call(b);var h;if(b.length&&E(h=b[b.length-1]))for(var f=0;f<d.length;f++)if(d[f]>=e){Object.assign(b[b.length-1]={},h);break}}e=b;c=!c;a=a.i;let k;for(h=0;h<d.length;h++)if(f=d[h],f<a){f+=-1;var g=e[f];null==g?e[f]=c?F:na([]):c&&g!==F&&ma(g)}else{if(!k){let n;e.length&&E(n=e[e.length-1])?k=n:e.push(k={})}g=k[f];null==k[f]?k[f]=c?F:na([]):c&&g!==F&&ma(g)}}return b};var ya=class extends S{},T=[2,3,4];var U=class extends S{};var V=class extends S{};var Ka=class extends S{};Ka.o=[6];var La=class extends S{constructor(){super()}};var Ma=class extends S{constructor(){super()}},Na=[2];var Oa=class extends S{};Oa.o=[2];var Pa=class extends S{};var Qa=class extends S{};var Ra=class extends S{};var Sa=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);b=Aa(a,oa(b))}return b}}(class extends S{}),K=[2,3,4,5,6,7];var W;var Va=function(a,b){this.i=a===Ta&&b||"";this.g=Ua},Ua={},Ta={};var Wa=class{constructor(a){this.g=a}toString(){return this.g+""}},Xa={};var Ya=function(){this.g=document||{cookie:""}};
Ya.prototype.set=function(a,b,c){let d,e,h,f=!1,g;"object"===typeof c&&(g=c.v,f=c.A||!1,h=c.domain||void 0,e=c.path||void 0,d=c.u);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.g.cookie=a+"="+b+(h?";domain="+h:"")+(e?";path="+e:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(f?";secure":"")+(null!=g?";samesite="+g:"")};
Ya.prototype.get=function(a,b){const c=a+"=",d=(this.g.cookie||"").split(";");for(let e=0,h;e<d.length;e++){h=aa(d[e]);if(0==h.lastIndexOf(c,0))return h.slice(c.length);if(h==a)return""}return b};/*

 SPDX-License-Identifier: Apache-2.0
*/
class Za{constructor(){this.i=new Ya;this.g="";this.j=a=>{a:{let k;try{k=Sa(a.data)}catch(n){break a}if(L(k,Ka,4)){var b=M(k,Ka,J(k,K,4)),c=za(b,6),d;c.length&&(d=$a(c));c={event:P(b,1)||void 0,category:P(b,2)||void 0,action:P(b,3)||void 0,label:P(b,4)||void 0,value:O(b,5)||void 0,nonInteraction:N(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==I(b,V,12,!1)){var e=M(b,V,12);c.recommendations={targetPage:P(e,1),targetType:O(e,2),targetRank:O(e,3),targetIdenticalDescriptions:O(e,4),targetTitleWords:O(e,
5),targetDescriptionWords:O(e,6),experiment:P(e,7)};d="";for(var h of window.dataLayer)if("experiment"in h&&"baseIds"in h.experiment){d=h.experiment.baseIds;break}(d=ab(d,P(e,7)))&&N(e,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var f of window.dataLayer)if("experiment"in f&&"ids"in f.experiment&&f.experiment.ids){c.experiment=
{ids:f.experiment.ids};break}h=M(b,U,11);if(void 0!==I(b,U,11,!1)&&null!==h){b=bb(h);for(var g of Object.keys(b))c[g]=b[g]}window.dataLayer.push(c)}else if(L(k,Oa,3)){b=M(k,Oa,J(k,K,3));c=za(b,2);let n;c.length&&(n=$a(c));c={event:"trackPageview",pageName:P(b,1),additionalParams:n||void 0,nonInteraction:N(b,3)||void 0,ratingsCount:O(b,4)||void 0,ratingsValue:O(b,5)||void 0};g=M(b,U,6);if(void 0!==I(b,U,6,!1)&&null!==g){b=bb(g);for(e of Object.keys(b))c[e]=b[e]}window.dataLayer.push(c)}else if(L(k,
Pa,7))b=M(k,Pa,J(k,K,7)),window.dataLayer.push({parentContext:{referrer:P(b,2)||"",_ga_devsiteCookie:P(b,1)||""}});else if(L(k,Qa,6))b=M(k,Qa,J(k,K,6)),c=this.g,g=M(b,V,9)||new V,h=P(b,10)||void 0,b={experiment:{ids:(N(g,8)?ab(h,P(g,7)):h)||void 0,baseIds:h||void 0},hostContext:{internalUser:P(b,1)||void 0,pageType:P(b,8)||void 0,projectName:P(b,6)||void 0,signedIn:P(b,2)||void 0,tenant:P(b,5)||void 0,thirdPartyCookieAccepted:c.length?"True":"False"},language:{machineTranslated:P(b,7)||void 0,requested:P(b,
3)||void 0,served:P(b,4)||void 0},recommendations:{sourcePage:P(g,1),sourceType:O(g,2),sourceRank:O(g,3),sourceIdenticalDescriptions:O(g,4),sourceTitleWords:O(g,5),sourceDescriptionWords:O(g,6),experiment:P(g,7)}},window.dataLayer.push(b);else if(L(k,Ra,5))b=M(k,Ra,J(k,K,5)),window.dataLayer.push({originalUrlParameters:{dclid:P(b,1)||void 0,gclid:P(b,2)||void 0,utmCampaign:P(b,3)||void 0,utmContent:P(b,4)||void 0,utmCreativeFormat:P(b,8)||void 0,utmMarketingTactic:P(b,10)||void 0,utmMedium:P(b,5)||
void 0,utmSource:P(b,6)||void 0,utmSourcePlatform:P(b,9)||void 0,utmTerm:P(b,7)||void 0}});else if(null!=ua(k,J(k,K,2))){window.dataLayer=window.dataLayer||[];window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"});g=document.getElementsByTagName("script")[0];h=document.createElement("script");h.async=!0;f=new Va(Ta,"//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG");f=f instanceof Va&&f.constructor===Va&&f.g===Ua?f.i:"type_error:Const";if(void 0===W)if(e=null,(d=l.trustedTypes)&&
d.createPolicy){try{e=d.createPolicy("goog#html",{createHTML:m,createScript:m,createScriptURL:m})}catch(n){l.console&&l.console.error(n.message)}W=e}else W=e;f=(e=W)?e.createScriptURL(f):f;e=new Wa(f,Xa);f=h;f.src=e instanceof Wa&&e.constructor===Wa?e.g:"type_error:TrustedResourceUrl";(b=(e=null==(c=(b=(f.ownerDocument&&f.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]"))?e.nonce||e.getAttribute("nonce")||"":"")&&f.setAttribute("nonce",b);g.parentNode.insertBefore(h,
g)}}};window.addEventListener("message",this.j)}s(a){this.g=this.i.get("_ga_devsite")||"";var b=new La;a=va(b,1,null==a?a:!!a,!1);b=va(a,2,this.g,"");a=new Ma;sa(B(a.h));null==b&&(b=void 0);sa(B(a.h));var c=wa(a,Na);c&&2!==c&&null!=b&&H(a,c,void 0,!1);a=H(a,2,b);if(window.parent!==window){b=window.parent;c=b.postMessage;a:{ra=!0;try{var d=JSON.stringify(a.toJSON(),Ba);break a}finally{ra=!1}d=void 0}c.call(b,d,"*")}}}Za.prototype.notifyIframeReady=Za.prototype.s;
function $a(a){const b={};for(const c of a){a=P(c,1);let d;P(c,J(c,T,2))?d=P(c,J(c,T,2)):O(c,J(c,T,3))?d=O(c,J(c,T,3)):null!=ua(c,J(c,T,4))&&(d=N(c,J(c,T,4))?"True":"False");b[a]=d}return b}
function bb(a){const b={};if(!a)return b;b.hasProfile=N(a,6)?"True":"False";b.practitionerType=P(a,1)||"Property not set";b.profileCreationMethod=P(a,4)||"Property not set";b.profileHasInterests=N(a,12)?"True":"False";b.profileInterests=P(a,13)||"Property not set";b.profileHasJobTitle=N(a,10)?"True":"False";b.profileHasLocation=N(a,7)?"True":"False";b.profileHasPronoun=N(a,9)?"True":"False";b.profileIsPublic=N(a,8)?"True":"False";b.profileSocialLinks=P(a,11)||"Property not set";b.profileBadgeEmailOptIn=
N(a,5)?"True":"False";b.profileFeedbackEmailOptIn=N(a,2)?"True":"False";b.profileNewsletterEmailOptIn=N(a,3)?"True":"False";return b}function ab(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var cb=Za,X=["AnalyticsLibrary"],Y=l;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===cb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=cb;}).call(this);
